// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SleepMonitor.Infrastructure.Persistence;

#nullable disable

namespace SleepMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(SleepMonitorDbContext))]
    [Migration("20241208163029_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SleepMonitor.Domain.Entities.IoTData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LightLevel")
                        .HasColumnType("float");

                    b.Property<double>("NoiseLevel")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("IoTData");
                });

            modelBuilder.Entity("SleepMonitor.Domain.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("SleepMonitor.Domain.Entities.SleepRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AvgLightLevel")
                        .HasColumnType("float");

                    b.Property<double>("AvgNoiseLevel")
                        .HasColumnType("float");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<DateTime>("SleepEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SleepStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SleepRecords");
                });

            modelBuilder.Entity("SleepMonitor.Domain.Entities.SleepRecord_Recommendation", b =>
                {
                    b.Property<Guid>("SleepRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SleepRecordId", "RecommendationId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("SleepRecord_Recommendations");
                });

            modelBuilder.Entity("SleepMonitor.Domain.Entities.SleepRecord_Recommendation", b =>
                {
                    b.HasOne("SleepMonitor.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SleepMonitor.Domain.Entities.SleepRecord", "SleepRecord")
                        .WithMany("SleepRecordRecommendations")
                        .HasForeignKey("SleepRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");

                    b.Navigation("SleepRecord");
                });

            modelBuilder.Entity("SleepMonitor.Domain.Entities.SleepRecord", b =>
                {
                    b.Navigation("SleepRecordRecommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
